### ISSUE TITLE
Full path of testing files too long on Windows

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [ARMmbed/mbed-client-mbed-tls#8] opened 2015-10-02 06:59 UTC
CMake/yotta complains on Windows that the path is too long. See below

```
-- The ASM compiler identification is GNU
-- Found assembler: C:/winapps/Eclipse_Toolchain/GNU_Tools_ARM_Embedded/4.9_2015q1/bin/arm-none-eabi-gcc.exe
GNU-ASM.cmake included
-- Configuring done
CMake Warning in ym/mbed-client-mbedtls/test/CMakeLists.txt:
  The object file directory

    C:/Users/Xxxxxx.Xxxxxx/GitRepos/mbed/xxxxxxx/xxxxxxxxxxxxx/build/st-nucleo-f401re-gcc/ym/mbed-client-mbedtls/test/CMakeFiles/mbed-client-mbedtls-test-mbed-client-mbed-tls.dir/

  has 175 characters.  The maximum full path to an object file is 250
  characters (see CMAKE_OBJECT_PATH_MAX).  Object file

    C_/Users/Xxxxxx.Xxxxxx/GitRepos/mbed/xxxxxxx/xxxxxxxxxxxxx/yotta_modules/mbed-client-mbedtls/test/mbed-client-mbed-tls/unittest/m2mconnectionsecuritypimpl_mbedtls/m2mconnectionsecuritypimpl_mbedtlstest.cpp.obj

  cannot be safely placed under this directory.  The build may not work
  correctly.
-- Generating done
```

Is it possible to shorten the filenames respectively test names?

**Comment by yogpan01** [comment] 2015-10-02 07:19
The right way to fix the issue is to handle it in yotta build command, yotta build should not try to build the tests of some internal component. Each component can have their own test structure and those tests should not be part of application's build system .
@autopulated Do you agree on this? Because this is not just the path problem but also issues with how yotta build is working currently.

**Comment by autopulated** [comment] 2015-10-02 08:45
yotta doesn't try to build the tests of anything other than the top-level module, so I'm not sure what's happening here – are you using yotta 0.8.1?

**Comment by markus-becker-tridonic-com** [comment] 2015-10-02 08:48
Yes, this is with yotta 0.8.1.
```
λ yotta --version
0.8.1
```

**Comment by autopulated** [comment] 2015-10-02 10:44
does the build go on to fail after the warning?

**Comment by markus-becker-tridonic-com** [comment] 2015-10-02 10:52
The build goes through as long as the files are only test files, but ```yotta clean``` will have troubles to remove those files later on.

**Comment by autopulated** [comment] 2015-10-02 11:53
> but yotta clean will have troubles to remove those files later on.

Is that speculation, or does it actually fail?

**Comment by markus-becker-tridonic-com** [comment] 2015-10-02 11:57
yotta clean fails (on Windows).

**Comment by autopulated** [comment] 2015-10-02 11:59
OK, thanks – that's definitely a problem. Anything that the build creates it should be able to remove.

**Comment by rainierwolfcastle** [comment] 2015-10-15 15:01
http://jira-dev0.cambridge.arm.com/browse/IOTCLT-270

**Comment by rainierwolfcastle** [comment] 2015-10-16 15:34
ARM Internal Ref: IOTCLT-359

**Comment by yogpan01** [comment] 2015-10-26 13:46
Closing this issue here as it will be handled on yotta side. https://github.com/ARMmbed/yotta/issues/536

**Closed** 2015-10-27 10:13 UTC
Labels: closed_in_jira, mirrored

**Comment by gamicklisafisher** [comment] 2015-11-22 07:01
You should check out ‘Long Path Tool’ it will help you fix the issues.
I had faced similar issue and this tool helped me to resolve this issue.
